targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "assets/openapi/"
          output_folder: "lib/api/generated/"
          separate_models: true