name: Create and populate .env file

on: [workflow_call]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Create .env file
        run: |
          cat > assets/.env <<EOF
          EOF