name: Create and populate .env file

on: [workflow_call]

jobs:
  build_env:
    runs-on: macos-latest
    steps:
      - name: Create .env file
        run: |
          echo "ls -a ."
          ls -a .
          
          touch .Renviron
          
          echo "cat .Renviron"
          cat .Renviron
          
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash