name: Create and populate .env file

on: [workflow_call]

jobs:
  build_env:
    runs-on: macos-latest
    steps:
      - name: Create .env file
        run: |
          echo "ls -a ."
          ls -a .
          
          touch .${{ github.workspace }}/.env
          
          echo "cat ./.env"
          cat ./lib/.env
          
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash