name: Create and populate .env file

on: [workflow_call]

jobs:
  build_env:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          touch .env
          
          echo "ls -a ."
          ls -a .
          
          echo "cat .env"
          cat .env
          
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash
      - name: Archive .env file
        uses: actions/upload-artifact@v3
        with:
          name: .env
          path: .env