name: Create and populate .env file

on: [workflow_call]

jobs:
  build_.env:
    runs-on: macos-latest
    steps:
      - name: env file creation
        uses: SpicyPizza/create-envfile@v1.3
        with:
          file_name: .env
          directory: './'