name: Running tests

on: [push]
jobs:
  env_workflow:
    uses: ./.github/workflows/create_env.yaml
  flutter_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: flutter test