name: Running tests

on: [push]
jobs:
  flutter_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: |
          touch .env

          echo "ls -a ."
          ls -a .

          echo "cat .env"
          cat .env

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash
      - run: flutter test