name: tests
on: [push]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: lib
          file_name: .env
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: flutter test